_target_: kfm.models.flow.MultiFlow
flows:
  kinetic:
    _target_: kfm.models.flow.KineticFlow
    prior:
      _target_: kfm.distributions.prior.KineticPrior
      zero_v0: ${zero_v0}
      zero_cog_v: ${zero_cog_v}
    path:
      #_target_: kfm.path.kinetic.KineticCubicProbPath
      _target_: kfm.path.kinetic.KineticQuinticProbPath
      #_target_: kfm.path.kinetic.StochasticKineticCubicProbPath
      manifold: ${manifold}
      simplified: ${simplified_parameterization}
    zero_v1: ${zero_v1}
    simplified: ${simplified_parameterization}
    zero_cog_v: ${zero_cog_v}

  lattice:
    _target_: kfm.models.flow.LatticeFlow
    prior:
      _target_: kfm.distributions.prior.IsotropicLatticePrior
    path:
      _target_: flow_matching.path.CondOTProbPath
