model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: ${monitor_metric}
  mode: max
  save_top_k: 3
  save_last: True
  verbose: false
  every_n_epochs: ${struct_eval_every_n_epoch}
  save_on_train_epoch_end: true
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: true
