structure_evaluator:
  _target_: kfm.utils.callbacks.StructureEvaluator
  generator:
    _target_: kfm.generator.kinetic.KineticCrystalFlowGenerator
    solver:
      _target_: kfm.solver.kinetic_solver.KineticCrystalODESolver
      manifold: ${manifold}
    transform_lengths: ${data_module.val_dataset.transform.transforms.1}
    transform_angles: ${data_module.val_dataset.transform.transforms.2}
    step_size: 0.001
    ode_method: euler
  metrics: ${metrics}
  eval_every_n_epochs: ${struct_eval_every_n_epoch}
